=encoding utf8

=head1 NAME

gesturetest - Test program for the X Gesture Stack

=head1 SYNOPSIS

gesturetest <window> <device> <gesture mask>

=head1 DESCRIPTION

B<gesturetest> is a program to test the X gesture extension and stack of
libraries. Invoke it with an X window ID, an X input device ID, and a bitmask
of gestures to listen for on the window. Selected gestures that occur within the
window will be written to stdout.

Note that gestures may be caught by windows above the selected window in the X
window hierarchy. When this occurs, the window above will receive the gesture,
but the window selected for B<gesturetest> will not.

To select for gestures from all input devices, use I<0> for the device ID. To
select for gestures on all windows, use I<0> for the window ID.

=head1 AUTHOR

Chase Dogulas <chase.douglas@canonical.com>

=head1 COPYRIGHT

Copyright 2010 by Canonical, Ltd.
Copyright 2001-2006 Bart Massey, Jamey Sharp, and Josh Triplett.
